"""create_initial_schema

Crea el esquema completo aprobado en 04_BASE_DATOS.md §9: 16 entidades, 4 tablas
de relacion N:M, restricciones, CHECKs e indices obligatorios de §9.6.

Reversible: downgrade() elimina el esquema completo, la funcion
immutable_unaccent y la extension unaccent.

Depende de: ninguna (revision inicial).

Revision ID: 85f7b1aa1535
Revises:
Create Date: 2026-08-09 17:27:32.381865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85f7b1aa1535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # AD-21 / RN-48: la busqueda ignora acentos y mayusculas. El indice
    # idx_products_search es una expresion, y PostgreSQL solo admite funciones
    # IMMUTABLE en indices. unaccent() se declara STABLE porque depende del
    # diccionario, asi que se envuelve en una funcion IMMUTABLE con el
    # diccionario fijado explicitamente (04_BASE_DATOS.md §9.6.2).
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION immutable_unaccent(text)
        RETURNS text
        LANGUAGE sql
        IMMUTABLE
        PARALLEL SAFE
        STRICT
        AS $$ SELECT public.unaccent('public.unaccent', $1) $$
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('administrator', 'super_administrator')", name=op.f('ck_administrators_role_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrators')),
    sa.UniqueConstraint('email', name=op.f('uq_administrators_email')),
    sa.UniqueConstraint('username', name=op.f('uq_administrators_username'))
    )
    op.create_table('banners',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name=op.f('ck_banners_window_ordered')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_banners_position_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banners'))
    )
    op.create_table('brands',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('slug', name=op.f('uq_brands_slug'))
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('parent_id IS NULL OR parent_id != id', name=op.f('ck_categories_parent_not_self')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index('idx_categories_parent_id', ['parent_id'], unique=False)

    op.create_table('colors',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('hex_code', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors')),
    sa.UniqueConstraint('slug', name=op.f('uq_colors_slug'))
    )
    op.create_table('genders',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genders')),
    sa.UniqueConstraint('name', name=op.f('uq_genders_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_genders_slug'))
    )
    op.create_table('size_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_size_types')),
    sa.UniqueConstraint('name', name=op.f('uq_size_types_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_size_types_slug'))
    )
    op.create_table('sports',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sports')),
    sa.UniqueConstraint('slug', name=op.f('uq_sports_slug'))
    )
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('business_hours', sa.Text(), nullable=True),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('item_template', sa.Text(), nullable=False),
    sa.Column('featured_products_count', sa.Integer(), server_default='8', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('featured_products_count > 0', name=op.f('ck_store_settings_featured_products_count_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_settings'))
    )
    op.create_table('audit_logs',
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("action IN ('create', 'update', 'delete', 'activate', 'deactivate')", name=op.f('ck_audit_logs_action_allowed')),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], name=op.f('fk_audit_logs_administrator_id_administrators'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_administrator_id', ['administrator_id'], unique=False)
        batch_op.create_index('idx_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('list_price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('sale_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_new', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('primary_category_id', sa.Integer(), nullable=False),
    sa.Column('size_type_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("availability IN ('available', 'low_stock', 'out_of_stock', 'coming_soon')", name=op.f('ck_products_availability_allowed')),
    sa.CheckConstraint('list_price > 0', name=op.f('ck_products_list_price_positive')),
    sa.CheckConstraint('sale_ends_at IS NULL OR sale_starts_at IS NULL OR sale_ends_at > sale_starts_at', name=op.f('ck_products_sale_window_ordered')),
    sa.CheckConstraint('sale_price IS NULL OR sale_price < list_price', name=op.f('ck_products_sale_price_below_list')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], name=op.f('fk_products_gender_id_genders'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_category_id'], ['categories.id'], name=op.f('fk_products_primary_category_id_categories'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_type_id'], ['size_types.id'], name=op.f('fk_products_size_type_id_size_types'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('idx_products_active_not_deleted', ['is_active', 'deleted_at'], unique=False)
        batch_op.create_index('idx_products_availability', ['availability'], unique=False)
        batch_op.create_index('idx_products_brand_id', ['brand_id'], unique=False)
        batch_op.create_index('idx_products_gender_id', ['gender_id'], unique=False)
        batch_op.create_index('idx_products_list_price', ['list_price'], unique=False)
        batch_op.create_index('idx_products_primary_category_id', ['primary_category_id'], unique=False)
        batch_op.create_index('idx_products_sale_dates', ['sale_starts_at', 'sale_ends_at'], unique=False)
        batch_op.create_index('idx_products_search', [sa.text('lower(immutable_unaccent(name))')], unique=False)
        batch_op.create_index('idx_products_size_type_id', ['size_type_id'], unique=False)

    op.create_table('sizes',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('slug', sa.String(length=20), nullable=False),
    sa.Column('size_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['size_type_id'], ['size_types.id'], name=op.f('fk_sizes_size_type_id_size_types'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sizes')),
    sa.UniqueConstraint('name', 'size_type_id', name='uq_sizes_name_size_type_id'),
    sa.UniqueConstraint('slug', name=op.f('uq_sizes_slug'))
    )
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.create_index('idx_sizes_size_type_id', ['size_type_id'], unique=False)

    op.create_table('images',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('position >= 0', name=op.f('ck_images_position_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_images_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index('idx_images_product_id', ['product_id'], unique=False)
        batch_op.create_index('uq_images_primary_per_product', ['product_id'], unique=True, postgresql_where=sa.text('is_primary = true AND deleted_at IS NULL'))

    op.create_table('price_history',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Integer(), nullable=False),
    sa.Column('new_price', sa.Integer(), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrators.id'], name=op.f('fk_price_history_administrator_id_administrators'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_price_history_product_id', ['product_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_product_categories_category_id_categories'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_categories_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name=op.f('pk_product_categories'))
    )
    op.create_table('product_colors',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_product_colors_color_id_colors'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_colors_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'color_id', name=op.f('pk_product_colors'))
    )
    op.create_table('product_sizes',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_sizes_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name=op.f('fk_product_sizes_size_id_sizes'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'size_id', name=op.f('pk_product_sizes'))
    )
    op.create_table('product_sports',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_sports_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], name=op.f('fk_product_sports_sport_id_sports'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('product_id', 'sport_id', name=op.f('pk_product_sports'))
    )
    op.create_table('promotions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(product_id IS NOT NULL)::int + (category_id IS NOT NULL)::int + (brand_id IS NOT NULL)::int = 1', name=op.f('ck_promotions_scope_exclusive')),
    sa.CheckConstraint('discount_percentage BETWEEN 1 AND 99', name=op.f('ck_promotions_discount_percentage_range')),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name=op.f('ck_promotions_window_ordered')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_promotions_brand_id_brands'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_promotions_category_id_categories'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_promotions_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions'))
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('idx_promotions_brand_id', ['brand_id'], unique=False)
        batch_op.create_index('idx_promotions_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_promotions_dates', ['starts_at', 'ends_at'], unique=False)
        batch_op.create_index('idx_promotions_product_id', ['product_id'], unique=False)

    op.create_table('variants',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_variants_color_id_colors'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_variants_product_id_products'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_id'], ['sizes.id'], name=op.f('fk_variants_size_id_sizes'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.create_index('idx_variants_color_id', ['color_id'], unique=False)
        batch_op.create_index('idx_variants_product_id', ['product_id'], unique=False)
        batch_op.create_index('idx_variants_size_id', ['size_id'], unique=False)
        batch_op.create_index('uq_variants_product_color_size', ['product_id', sa.text('COALESCE(color_id, 0)'), sa.text('COALESCE(size_id, 0)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_index('uq_variants_product_color_size', postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index('idx_variants_size_id')
        batch_op.drop_index('idx_variants_product_id')
        batch_op.drop_index('idx_variants_color_id')

    op.drop_table('variants')
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_index('idx_promotions_product_id')
        batch_op.drop_index('idx_promotions_dates')
        batch_op.drop_index('idx_promotions_category_id')
        batch_op.drop_index('idx_promotions_brand_id')

    op.drop_table('promotions')
    op.drop_table('product_sports')
    op.drop_table('product_sizes')
    op.drop_table('product_colors')
    op.drop_table('product_categories')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('idx_price_history_product_id')

    op.drop_table('price_history')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('uq_images_primary_per_product', postgresql_where=sa.text('is_primary = true AND deleted_at IS NULL'))
        batch_op.drop_index('idx_images_product_id')

    op.drop_table('images')
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.drop_index('idx_sizes_size_type_id')

    op.drop_table('sizes')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_products_size_type_id')
        batch_op.drop_index('idx_products_search')
        batch_op.drop_index('idx_products_sale_dates')
        batch_op.drop_index('idx_products_primary_category_id')
        batch_op.drop_index('idx_products_list_price')
        batch_op.drop_index('idx_products_gender_id')
        batch_op.drop_index('idx_products_brand_id')
        batch_op.drop_index('idx_products_availability')
        batch_op.drop_index('idx_products_active_not_deleted')

    op.drop_table('products')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_entity')
        batch_op.drop_index('idx_audit_logs_administrator_id')

    op.drop_table('audit_logs')
    op.drop_table('store_settings')
    op.drop_table('sports')
    op.drop_table('size_types')
    op.drop_table('genders')
    op.drop_table('colors')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index('idx_categories_parent_id')

    op.drop_table('categories')
    op.drop_table('brands')
    op.drop_table('banners')
    op.drop_table('administrators')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS immutable_unaccent(text)")
    op.execute("DROP EXTENSION IF EXISTS unaccent")
