"""create_banks_table

Tabla nueva para Superdescuentos (04_BASE_DATOS.md §9.2.13): nombre, porcentaje
de descuento (1-99, mismo rango que `promotions`), mini banner y orden. Entidad
propia, no una extensión de `promotions` ni de `banners` (ver `models/bank.py`).

Revision ID: e2db739a4c13
Revises: c5b1f0a72e14
Create Date: 2026-09-22 13:03:55.310300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2db739a4c13'
down_revision = 'c5b1f0a72e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('discount_percentage BETWEEN 1 AND 99', name=op.f('ck_banks_discount_percentage_range')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_banks_position_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banks'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banks')
    # ### end Alembic commands ###
